# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hi-Efficiency Bar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'TPKeyboardAvoiding'
  # Pods for Hi-Efficiency Bar
 pod 'MXParallaxHeader'
end
